name: Production Environment S3 Deploy
on:
  push:
    branches: main

jobs:
  main-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_EC2_METADATA_DISABLED: true 
      REACT_APP_ENV: production
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: deploy
        run: aws s3 sync ./build/ s3://brannigans-chess/

      - name: invalidate
        run: aws cloudfront create-invalidation --distribution-id E2EJVD2IGAS1MY --paths "/*"
